### ISSUE TITLE
Add redirect to https website

### ISSUE THREAD

**Issue by arthrp** [AvaloniaUI/avaloniaui.net#103]
Currently links from google and other search engines point to http version of the site. Would be nice to redirect users to the secure one.

**Comment by kekekeks** [comment]
With more and more countries introducing DPI and censorship systems that are randomly blocking HTTPS content they don't recognize, I'd rather avoid *enforcing* https on people who won't be able to use it.

**Comment by arthrp** [comment]
It's a sad day when one chooses to make web less secure because of governmental censorship, but I understand your motivation. Maybe then a collapsable block with warning for those of us who didn't notice that no redirection took place (I'm sure that I'm not the only one)?
