### ISSUE TITLE
PropertyChangedCallback section has a broken link

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/avaloniaui.net#113]
[PropertyChangedCallback](http://avaloniaui.net/docs/quickstart/from-wpf#propertychangedcallback)
contains invalid link to http://avaloniaui.net/docs/quickstart/working-with-properties.md#subscribing-to-a-property-on-any-object

Copied from [gitter](https://gitter.im/AvaloniaUI/Avalonia?at=5e5573f3901209179b3c4e84)

**Comment by grokys** [comment]
Fixed by #131
