### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/avaloniaui.net#115]
Currently docs is C#-oriented but there are other languages like F#, VB.Net. etc.

Not sure how popular Avalonia among Vb.net developers but I know there are users that prefer F# for Avalonia. 

So, I think it will be great to see some article or even section that explains key concepts relatively to F#.

**Comment by kekekeks** [comment]
Unfortunately, there are no devs with proper F# knowledge in the core team. So while we are doing our best effort to keep the framework F# friendly (we even have some F#-specific hacks in our XAML compiler) we aren't qualified to write F# docs.

Contributions are welcome.

**Comment by JamRemco** [comment]
how about Project templates for VB.net and F#?

Remco

**Comment by FoggyFinder** [comment]
> how about Project templates for VB.net and F#?

@JamRemco  There is a PR for F# template [add basic F# template #16](https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/16). Not sure what status it has now

**Comment by JaggerJo** [comment]
@FoggyFinder I think it needs to be updated to 0.10 (it's currently for 0.8.x IIRC)
