### ISSUE TITLE
Hard to read text 

### ISSUE THREAD

**Issue by JamRemco** [AvaloniaUI/avaloniaui.net#138]
New site looks great, but I think this not the right color palette
![image](https://user-images.githubusercontent.com/58340108/80236329-4a9a6600-865b-11ea-9f82-178158c48d0a.png)

Regards,

Remco

**Comment by FoggyFinder** [comment]
Was it resolved?

**Comment by JamRemco** [comment]
Nope. the support pages still looks like that. 
but wait there is more i've got the dark reader plugin enabled. Without it looks like this
![image](https://user-images.githubusercontent.com/58340108/81006060-2dca1380-8e4f-11ea-827b-ab03b806e35f.png)

Oke that is way more readable but i know some folks like the dark reader plug in on there brouwser.

Just saying

Regards, 

Remco

**Comment by robloo** [comment]
This should be closed. The website was completely redesigned and this is no longer applicable.
