### ISSUE TITLE
"Contributing" page looks too narrow

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/avaloniaui.net#139]
![Avalonia Support-1](https://user-images.githubusercontent.com/16510738/80394573-b4647b00-88ba-11ea-90ac-0344907f66ba.jpg)

**Comment by Carlos487** [comment]
@grokys I can help with this one. If no one else is working on it. Which is the correct branch asp-net-core or new-site?

**Comment by Gillibald** [comment]
The new site will be soon merged into master

**Comment by grokys** [comment]
@Carlos487 as @Gillibald says, i will merge the new site to master soon (a few things to fix up with CI first) but in the meantime `new-site` is the branch you want to be working against if you'd like to help out!

**Comment by grokys** [comment]
Fixed by https://github.com/AvaloniaUI/avaloniaui.net/pull/147
