### ISSUE TITLE
Text on docs pages is cut off at beginning

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/avaloniaui.net#153]
It seems as though the first couple letters (letter?) are/is sometimes getting chopped off when displaying the docs. See the tutorial index page ("n this tutorial"):

<img width="401" alt="Screen Shot 2020-05-05 at 10 12 55 AM" src="https://user-images.githubusercontent.com/5092399/81075973-0f98fd80-8eb9-11ea-9f12-8322449e5538.png">

But the [actual file](https://github.com/AvaloniaUI/avaloniaui.net/blob/master/src/AvaloniaUI.Net/wwwroot/docs/tutorial/index.md) looks OK and has the correct text at the beginning ("In this tutorial").

I also found this issue on [the reactive UI page](http://avaloniaui.net/docs/reactiveui/) and the [ReactiveUI data persistence page](http://avaloniaui.net/docs/reactiveui/suspension). Probably in other places too.

**Comment by Carlos487** [comment]
I checked that in a locally build version of master branch, as it is not happening, but on the real website it is still occurring. Maybe it is a FrontMatter configuration or something happening during the release/publish workflow.
![2020-05-09 09_45_10-Window](https://user-images.githubusercontent.com/1598555/81476889-133ec400-91da-11ea-93c0-6a806b472a79.png)

**Comment by ForNeVeR** [comment]
I've managed to reproduce and fix this madness, see #158.
