### ISSUE TITLE
Some of the blog posts have their first letter lost

### ISSUE THREAD

**Issue by ForNeVeR** [AvaloniaUI/avaloniaui.net#157]
For example:
- http://avaloniaui.net/docs/quickstart/change-target-framework
  ![image](https://user-images.githubusercontent.com/92793/82152106-5dced900-9889-11ea-9017-c982cbb47b82.png)
- http://avaloniaui.net/docs/quickstart/intro-to-xaml
  ![image](https://user-images.githubusercontent.com/92793/82152110-658e7d80-9889-11ea-9317-9a422a5b9452.png)

**Comment by FoggyFinder** [comment]
Duplicate of #153 ?

**Comment by ForNeVeR** [comment]
Yeah, thanks!
