### ISSUE TITLE
Add documentation on StyleInclude/ResourceInclude

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/avaloniaui.net#160]
https://github.com/AvaloniaUI/Avalonia/issues/3978

**Comment by Ace4896** [comment]
I recently worked on something where I wanted to keep styles in separate files, mind if I have a go at writing this? I noticed that there's already some documentation for [ResourceInclude](https://avaloniaui.net/docs/styles/resources#merged-resource-dictionaries) though; do you think it needs to be expanded anywhere?

**Comment by grokys** [comment]
@Ace4896 yes, please do!
