### ISSUE TITLE
Font awesome is not working

### ISSUE THREAD

**Issue by Carlos487** [AvaloniaUI/avaloniaui.net#174]
Hi, I was trying to add the one icon and then I found out the following:

- Font awesome reference is missing the base css so it is not working 
- The library is not being used on the site at all

Here my question is, should I update, fix the reference to be used only in one icon (the one I'm adding)? Or should I remove it so it does not make an unnecessary request?

Please let me know I will be willing to work on it and implement the PR.

**Comment by Carlos487** [comment]
Hi @grokys do you have any comment on this issue?

**Comment by grokys** [comment]
Hi @Carlos487, sorry i was on vacation. Your fix in #182 looks good to me.
