### ISSUE TITLE
Update docs to remove Serilog mentions

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avaloniaui.net#181]
With 0.10.0 Avalonia doesn't use Serilog anymore.
Related page in the documentation should be updated:
http://avaloniaui.net/docs/quickstart/logging

**Comment by robloo** [comment]
I believe the new link is: https://docs.avaloniaui.net/docs/getting-started/logging-errors-and-warnings

It seems Serilog references were already removed and this can be closed.
