### ISSUE TITLE
ComboBox has SelectionMode protected

### ISSUE THREAD

**Issue by mishun** [AvaloniaUI/avaloniaui.net#201]
Hi!
ComboBox is inherited from SelectingItemsControl where SelectionMode is declared as protected. As I could see, ListBox works around that like that:
```C#
        public new SelectionMode SelectionMode
        {
            get { return base.SelectionMode; }
            set { base.SelectionMode = value; }
        }
```
but that is not the case for ComboBox. Documentation at https://avaloniaui.net/docs/controls/combobox suggests that SelectionMode should be accessible. Is this a mistake in documentation or implementation?

**Comment by Mbucari** [comment]
The docs page still lists SelectionMode as a property.
https://docs.avaloniaui.net/docs/controls/combobox
