### ISSUE TITLE
Link hard coded to localhost.

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/avaloniaui.net#202]
Within the ToDo tutorial, on the creating the project page, the link to the "Intro To XAML" page near the bottom is hardcoded to local host.  So on https://avaloniaui.net/docs/tutorial/creating-the-project, the link does not work.

**Comment by FoggyFinder** [comment]
Nice catch. Would you like to create PR with fix?

**Comment by mrj001** [comment]
OK
