### ISSUE TITLE
dotnet run not working

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/avaloniaui.net#204]
To reproduce:
```
$ dotnet run
```
Go to a web browser, and enter http://localhost:5000.
Click on Get Started, and get error:

Here is the output in the terminal window:

> info: Microsoft.Hosting.Lifetime[0]
>       Now listening on: https://localhost:5001
> info: Microsoft.Hosting.Lifetime[0]
>       Now listening on: http://localhost:5000
> info: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> info: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Development
> info: Microsoft.Hosting.Lifetime[0]
>       Content root path: /Users/mj/Documents/develop/avalonia.learn/avaloniaui.net/src/AvaloniaUI.Net
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
> YamlDotNet.Core.SyntaxErrorException: (Line: 2, Col: 6, Idx: 10) - (Line: 2, Col: 6, Idx: 10): Mapping values are not allowed in this context.
>    at YamlDotNet.Core.Scanner.FetchValue()
>    at YamlDotNet.Core.Scanner.FetchNextToken()
>    at YamlDotNet.Core.Scanner.FetchMoreTokens()
>    at YamlDotNet.Core.Scanner.MoveNextWithoutConsuming()
>    at YamlDotNet.Core.Parser.GetCurrentToken()
>    at YamlDotNet.Core.Parser.ParseDocumentEnd()
>    at YamlDotNet.Core.Parser.StateMachine()
>    at YamlDotNet.Core.Parser.MoveNext()
>    at YamlDotNet.Core.ParserExtensions.TryConsume[T](IParser parser, T& event)
>    at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
>    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
>    at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
>    at AvaloniaUI.Net.Services.MarkdownDocumentLoader.ParseFrontMatter[TFrontMatter](StreamReader r) in /Users/mj/Documents/develop/avalonia.learn/avaloniaui.net/src/AvaloniaUI.Net/Services/MarkdownDocumentLoader.cs:line 59
>    at AvaloniaUI.Net.Services.MarkdownDocumentLoader.LoadFrontMatter[TFrontMatter](String path) in /Users/mj/Documents/develop/avalonia.learn/avaloniaui.net/src/AvaloniaUI.Net/Services/MarkdownDocumentLoader.cs:line 45
>    at AvaloniaUI.Net.Pages.Docs.IndexModel.LoadFrontMatter(String path) in /Users/mj/Documents/develop/avalonia.learn/avaloniaui.net/src/AvaloniaUI.Net/Pages/Docs/Index.cshtml.cs:line 153
>    at AvaloniaUI.Net.Pages.Docs.IndexModel.LoadIndex(String path, String selectedPath) in /Users/mj/Documents/develop/avalonia.learn/avaloniaui.net/src/AvaloniaUI.Net/Pages/Docs/Index.cshtml.cs:line 90
>    at AvaloniaUI.Net.Pages.Docs.IndexModel.LoadIndex(String path, String selectedPath) in /Users/mj/Documents/develop/avalonia.learn/avaloniaui.net/src/AvaloniaUI.Net/Pages/Docs/Index.cshtml.cs:line 109
>    at AvaloniaUI.Net.Pages.Docs.IndexModel.OnGet(String url) in /Users/mj/Documents/develop/avalonia.learn/avaloniaui.net/src/AvaloniaUI.Net/Pages/Docs/Index.cshtml.cs:line 44
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> 

Here is the output of my "dotnet --info"

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.401
>  Commit:    39d17847db
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/3.1.401/
> 
> Host (useful for support):
>   Version: 3.1.7
>   Commit:  fcfdef8d6b
> 
> .NET Core SDKs installed:
>   3.1.200 [/usr/local/share/dotnet/sdk]
>   3.1.201 [/usr/local/share/dotnet/sdk]
>   3.1.300 [/usr/local/share/dotnet/sdk]
>   3.1.301 [/usr/local/share/dotnet/sdk]
>   3.1.302 [/usr/local/share/dotnet/sdk]
>   3.1.401 [/usr/local/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> 

I tried Safari and Firefox browsers on Mac, and Chrome on Windows.

**Comment by kekekeks** [comment]
Probably has something to do with line endings again.

@grokys

**Comment by rstm-sf** [comment]
@mrj001 this work  #208?
