### ISSUE TITLE
Typo on TabControl page

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/avaloniaui.net#206]
On the TabControl Page,
https://avaloniaui.net/docs/controls/tabcontrol

between the first and second image, the word "individual" is spelled "indivual".

**Comment by FoggyFinder** [comment]
Issue should be closed. Next time you can use one of the keywords

[Linking a pull request to an issue using a keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

I.e. with space: "KEYWORD #ISSUE-NUMBER"
