### ISSUE TITLE
Avalonia Tutorial Issue

### ISSUE THREAD

**Issue by jonathanBell1** [AvaloniaUI/avaloniaui.net#216]
We are evaluating Avalonia to build a UI to run Linux and Windows.  When I got to the end of the second part "Creating a View", the project would no longer compile. See attached
![AvalonError](https://user-images.githubusercontent.com/73142373/96516491-e1239a80-122c-11eb-959a-a13183a0fb3e.png)

When I remove the line =>   <views:TodoListView/>, I get the following error:
![AvalonError2](https://user-images.githubusercontent.com/73142373/96516899-8d658100-122d-11eb-9ab5-bb91303338f3.jpg)

**Comment by FoggyFinder** [comment]
Window can have only one child element. Try to remove all lines after `<views:TodoListView />` so it would match the code in the tutorial:

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:views="clr-namespace:Todo.Views"
        x:Class="Todo.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Width="200" Height="300"
        Title="Avalonia Todo">
  <views:TodoListView/>
</Window>
```

**Comment by maxkatz6** [comment]
To put more than one item inside you need to use container. There are Grid, StackPanel, DockPanel and other. You can find them in tutorials and documentation.

**Comment by jonathanBell1** [comment]
I tried that but now no matter what I do, even if I back out all of the changes I made to the project and get back the to original project created in step one by Visual Studio, I still get the following.:
![AvalonError2](https://user-images.githubusercontent.com/73142373/96607356-e7158c00-12bd-11eb-9bf1-d6668cff2a75.jpg)

**Comment by FoggyFinder** [comment]
Can you attach an archive to the comment? Then we'll be able to take a look

**Comment by jonathanBell1** [comment]
I have discovered that if I start a new Avalonia project, it will compile the first time.  If I do a rebuild, I get the following error:
Error	CS2012	Cannot open 'C:\Avalonia\MyToDo\ToDo\obj\Debug\netcoreapp3.1\ToDo.dll' for writing -- 'Access to the path 'C:\Avalonia\MyToDo\ToDo\obj\Debug\netcoreapp3.1\ToDo.dll' is denied.'	ToDo	C:\Avalonia\MyToDo\ToDo\CSC	1	Active

If I delete the ...Debug\netcoreapp3.1 directory, it will compile the first time then get that error again.  I also have to  get Admin privileges to to delete that directory.  I assume that is why the error is that the ToDo.dll file cannot be accessed. Is their a configuration to remove the Admin access for this directory.
