### ISSUE TITLE
Tutorial: The Todo app doesn't look like in the tutorial

### ISSUE THREAD

**Issue by ruilvo** [AvaloniaUI/avaloniaui.net#234]
Hey, I believe it might be because of the introduction of the Fluent theme but, for me, the UI I built using Avalonia 0.10 doesn't look like it does in the tutorial:

In my app:
![imagem](https://user-images.githubusercontent.com/8402646/106387265-ea4a0900-63d0-11eb-8dba-9154e6f5d262.png)
In the tutorial:
![av](https://avaloniaui.net/docs/tutorial/images/creating-a-view-run.png)

In my app:
![imagem](https://user-images.githubusercontent.com/8402646/106387293-0a79c800-63d1-11eb-8963-2b743579adb6.png)
In the tutorial:
![avt](https://avaloniaui.net/docs/tutorial/images/adding-new-items-view.png)

In particular, you see the buttons do not span the whole width of the Window.

Maybe that can be explained? Thanks!

**Comment by maxkatz6** [comment]
Fluent theme has another defaults for horizontal alignment of Buttons.
