### ISSUE TITLE
Wrong image link in docs

### ISSUE THREAD

**Issue by tupieurods** [AvaloniaUI/avaloniaui.net#270]
https://docs.avaloniaui.net/guides/basics/mvvm

![image](https://user-images.githubusercontent.com/3098011/118920550-d4049080-b960-11eb-9f4f-1487c06aa09e.png)

I think it supposed to look like this: https://github.com/AvaloniaUI/avaloniaui.net/blob/3c42837da72867839640f251feef66e1d10ce5d9/src/AvaloniaUI.Net/wwwroot/docs/quickstart/mvvm.md

But seems like image link was broken in the process of docs migration.

**Comment by robloo** [comment]
@tupieurods I believe this was fixed. Could you review and close this?

![image](https://user-images.githubusercontent.com/17993847/125559343-e5a6ce50-8c41-40b8-acca-6d3bfb15deb0.png)
