### ISSUE TITLE
Some Links in sections in "WPF Developers Tips" leads to 404

### ISSUE THREAD

**Issue by Outreaver** [AvaloniaUI/avaloniaui.net#273]
Link with 404 - Not Found below (Section - text in section with link):
1.  Styling - `CSS-like styling system`
2.  DependencyProperty - `has a richer property system than WPF`
3.  PropertyChangedCallback - `added to the control's static constructor in much the same way that event class listeners are added`

![obraz](https://user-images.githubusercontent.com/31647708/119566802-d9703980-bdab-11eb-950f-9d73091c1f83.png)

**Comment by FoggyFinder** [comment]
It's open source you can fix typos with PR. For example, file for `Styling` is located here

https://github.com/AvaloniaUI/Documentation/blob/master/misc/wpf/styling.md

Just replace the link with the right one and so on.

**Comment by Outreaver** [comment]
My screenshot is misleading. The problem is not with Sections like Styling. The problem is with some links that are attached to texts is thode sections that i pointed out after dashes. For example for point 1.
![obraz](https://user-images.githubusercontent.com/31647708/119572396-f3f9e100-bdb2-11eb-9887-8af341fcde76.png)

Unfortunately links in md files also lead to 404 and i don't know the correct ones so i can't fix this.

**Comment by robloo** [comment]
I just noticed this too: https://docs.avaloniaui.net/misc/wpf/propertychangedcallback

![image](https://user-images.githubusercontent.com/17993847/119575476-1a088c80-bd85-11eb-8e0d-2796a6109192.png)

**Comment by robloo** [comment]
I just fixed the one I noticed. You can look at the existing link and figure out the new docs location relatively easy.
