### ISSUE TITLE
Broken link to change notifications on bindings section

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/avaloniaui.net#45]
[Bindings](https://github.com/AvaloniaUI/avaloniaui.net/blob/master/wwwroot/docs/binding/bindings.md#title-bindingsorder-10)

Link to  **_change notifications_** is broken.

Saw report in [gitter](https://gitter.im/AvaloniaUI/Avalonia?at=5c5180c2975714406b6650f2), just decided to put it here to visibility.

**Comment by grokys** [comment]
Thanks! This documentation hasn't actually been written yet, which is why it's failing. Need to write it...
