### ISSUE TITLE
Typo on deployed support page

### ISSUE THREAD

**Issue by davidchavezgrant** [AvaloniaUI/avaloniaui.net#494]
See "tailered" on https://avaloniaui.net/Support

![Screenshot 2023-05-10 at 3 54 23 PM](https://github.com/AvaloniaUI/avaloniaui.net/assets/81833119/18169fb0-3df5-47eb-abc2-df9a8792c54c)

It seems to be something different in this repo, so perhaps a redeploy is needed?

**Comment by Arhell** [comment]
@MikeCodesDotNET take a look please

**Comment by MikeCodesDotNET** [comment]
I’ll get that fixed

**Comment by MikeCodesDotNET** [comment]
Fixed
