### ISSUE TITLE
Add documentation for creating templated controls

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/avaloniaui.net#73]

**Comment by rollersteaam** [comment]
Hello :) Probably after https://github.com/AvaloniaUI/avaloniaui.net/pull/169 has been cleared I'm feeling I want to take a crack at doing this. I've only been able to figure out how to do it for `UserControl`s so far, so hopefully when I send in a PR you'll probably be able to show me (if I can't figure it out myself when I get to it) how to correct it to fit the requirements of `TemplatedControl`s.

**Comment by grokys** [comment]
That would be great @rollersteaam - a while ago i started on https://github.com/grokys/StarRatingTutorial as a base for a tutorial on creating a simple templated control. It's using a slightly old version of Avalonia by now, and I'm not 100% convinced that this is the _best_ control to use to demonstrate but it may be helpful to you/work as a starting point.
