### ISSUE TITLE
Add .UseReactiveUI() in the tutorial

### ISSUE THREAD

**Issue by patrick-a-cavanaugh** [AvaloniaUI/avaloniaui.net#75]
I just went through [the tutorial ](http://avaloniaui.net/docs/tutorial/)and hit an issue where clicking either the Cancel/Ok buttons resulted in an exception "System.InvalidOperationException: Call from invalid thread " as in https://github.com/AvaloniaUI/Avalonia/issues/1934

I found that adding `.UseReactiveUI()` to the default Program.cs file created by the Avalonia MVVM template fixed it. This step should probably be added in the tutorial as well?

**Comment by wangfu91** [comment]
Also hit this issue, adding ```.UseReactiveUI()``` fixed it.

**Comment by grokys** [comment]
Thanks for reporting this! The problem is actually that the template is missing that line in the VS extension. I thought I'd published a new version with that fix but obviously not. I will push a new version of the VS extension to the VS marketplace.

**Comment by grokys** [comment]
I've just uploaded version 0.8.0.2 of the VS extension to the marketplace, which should fix this issue.

**Comment by unominhtuan** [comment]
add .UseReactiveUI() but not fixed
