### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by markrendle** [AvaloniaUI/avaloniaui.net#9]
Hi. Can I suggest using CloudFlare to add HTTPS to the website? It's totally free, really easy, and makes things look a little more professional.

**Comment by kekekeks** [comment]
The problem about CloudFlare is that it gets its IPs constantly banned in certain countries because of "prohibited" sites that are using it.

**Comment by webprofusion-chrisc** [comment]
Further to this, does anyone need any help on this? Looks like the site is hosted on ubuntu using nginx, so certbot or at least acme.sh should be configurable. acme.sh has the advantage of requiring less dependencies. 

If this site is fully static output it could even be hosted on github pages, then they can allocate the certificates (like I use for https://docs.certifytheweb.com)

**Comment by MarkusKgit** [comment]
I don't want to raise a new issue for this as it kinda fits here. The description of this repo at the very top still points to the http variant.

**Comment by grokys** [comment]
Thanks for pointing that out @MarkusKgit, fixed to use https. Going to close this now as it's been fixed for a while.
